import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        emergency: "Emergency / SOS",
        ambulances: "Nearby Ambulances",
        hospitals: "Nearby Hospitals",
        route: "Emergency Route",
        medicine: "Medicine Store",
        history: "Emergency History",
        profile: "My Profile",
        language: "Language",
        howWorks: "How RESQ Works",
        about: "About RESQ",
        logout: "Logout",
        welcome: "Welcome",
        quickAccess: "Quick Access",
        nearbyHospitals: "Nearby Hospitals",
        nearbyAmbulances: "Nearby Ambulances",
        emergencyRoute: "Emergency Route",
        medicineStore: "Medicine Store",
        currentLocation: "Current Location",
        callNow: "Call Now",
        getDirections: "Get Directions",
        backDashboard: "Back to Dashboard",
        saveLanguage: "Save Language",
        selectedLanguage: "Selected Language",
        languageChanged: "Language changed successfully.",
        chooseLanguage: "Choose your preferred language",
        languagesAvailable: "languages available",
    },

    te: {
        dashboard: "డ్యాష్‌బోర్డ్",
        emergency: "అత్యవసరం / SOS",
        ambulances: "దగ్గరలోని అంబులెన్స్‌లు",
        hospitals: "దగ్గరలోని ఆసుపత్రులు",
        route: "అత్యవసర మార్గం",
        medicine: "మెడిసిన్ స్టోర్",
        history: "అత్యవసర చరిత్ర",
        profile: "నా ప్రొఫైల్",
        language: "భాష",
        howWorks: "RESQ ఎలా పనిచేస్తుంది",
        about: "RESQ గురించి",
        logout: "లాగ్ అవుట్",
        welcome: "స్వాగతం",
        quickAccess: "త్వరిత ప్రాప్యత",
        nearbyHospitals: "దగ్గరలోని ఆసుపత్రులు",
        nearbyAmbulances: "దగ్గరలోని అంబులెన్స్‌లు",
        emergencyRoute: "అత్యవసర మార్గం",
        medicineStore: "మెడిసిన్ స్టోర్",
        currentLocation: "ప్రస్తుత స్థానం",
        callNow: "ఇప్పుడే కాల్ చేయండి",
        getDirections: "దారి చూపించు",
        backDashboard: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి",
        saveLanguage: "భాషను సేవ్ చేయండి",
        selectedLanguage: "ఎంచుకున్న భాష",
        languageChanged: "భాష విజయవంతంగా మార్చబడింది.",
        chooseLanguage: "మీకు సౌకర్యంగా ఉన్న భాషను ఎంచుకోండి",
        languagesAvailable: "భాషలు అందుబాటులో ఉన్నాయి",
    },

    hi: {
        dashboard: "डैशबोर्ड",
        emergency: "आपातकाल / SOS",
        ambulances: "नज़दीकी एम्बुलेंस",
        hospitals: "नज़दीकी अस्पताल",
        route: "आपातकालीन मार्ग",
        medicine: "मेडिसिन स्टोर",
        history: "आपातकालीन इतिहास",
        profile: "मेरी प्रोफ़ाइल",
        language: "भाषा",
        howWorks: "RESQ कैसे काम करता है",
        about: "RESQ के बारे में",
        logout: "लॉग आउट",
        welcome: "स्वागत है",
        quickAccess: "त्वरित पहुँच",
        nearbyHospitals: "नज़दीकी अस्पताल",
        nearbyAmbulances: "नज़दीकी एम्बुलेंस",
        emergencyRoute: "आपातकालीन मार्ग",
        medicineStore: "मेडिसिन स्टोर",
        currentLocation: "वर्तमान स्थान",
        callNow: "अभी कॉल करें",
        getDirections: "दिशा प्राप्त करें",
        backDashboard: "डैशबोर्ड पर वापस जाएँ",
        saveLanguage: "भाषा सेव करें",
        selectedLanguage: "चयनित भाषा",
        languageChanged: "भाषा सफलतापूर्वक बदल गई।",
        chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
        languagesAvailable: "भाषाएँ उपलब्ध हैं",
    },

    ta: {
        dashboard: "டாஷ்போர்டு",
        emergency: "அவசரம் / SOS",
        ambulances: "அருகிலுள்ள ஆம்புலன்ஸ்கள்",
        hospitals: "அருகிலுள்ள மருத்துவமனைகள்",
        route: "அவசர பாதை",
        medicine: "மருந்தகம்",
        history: "அவசர வரலாறு",
        profile: "என் சுயவிவரம்",
        language: "மொழி",
        howWorks: "RESQ எப்படி செயல்படுகிறது",
        about: "RESQ பற்றி",
        logout: "வெளியேறு",
        welcome: "வரவேற்கிறோம்",
        quickAccess: "விரைவு அணுகல்",
        nearbyHospitals: "அருகிலுள்ள மருத்துவமனைகள்",
        nearbyAmbulances: "அருகிலுள்ள ஆம்புலன்ஸ்கள்",
        emergencyRoute: "அவசர பாதை",
        medicineStore: "மருந்தகம்",
        currentLocation: "தற்போதைய இருப்பிடம்",
        callNow: "இப்போது அழைக்கவும்",
        getDirections: "வழியைப் பெறுங்கள்",
        backDashboard: "டாஷ்போர்டுக்குத் திரும்பு",
        saveLanguage: "மொழியைச் சேமிக்கவும்",
        selectedLanguage: "தேர்ந்தெடுக்கப்பட்ட மொழி",
        languageChanged: "மொழி வெற்றிகரமாக மாற்றப்பட்டது.",
        chooseLanguage: "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
        languagesAvailable: "மொழிகள் கிடைக்கின்றன",
    },

    kn: {
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        emergency: "ತುರ್ತು / SOS",
        ambulances: "ಹತ್ತಿರದ ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳು",
        hospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು",
        route: "ತುರ್ತು ಮಾರ್ಗ",
        medicine: "ಮೆಡಿಸಿನ್ ಸ್ಟೋರ್",
        history: "ತುರ್ತು ಇತಿಹಾಸ",
        profile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
        language: "ಭಾಷೆ",
        howWorks: "RESQ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
        about: "RESQ ಬಗ್ಗೆ",
        logout: "ಲಾಗ್ ಔಟ್",
        welcome: "ಸ್ವಾಗತ",
        quickAccess: "ತ್ವರಿತ ಪ್ರವೇಶ",
        nearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು",
        nearbyAmbulances: "ಹತ್ತಿರದ ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಳು",
        emergencyRoute: "ತುರ್ತು ಮಾರ್ಗ",
        medicineStore: "ಮೆಡಿಸಿನ್ ಸ್ಟೋರ್",
        currentLocation: "ಪ್ರಸ್ತುತ ಸ್ಥಳ",
        callNow: "ಈಗ ಕರೆ ಮಾಡಿ",
        getDirections: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ",
        backDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        saveLanguage: "ಭಾಷೆಯನ್ನು ಉಳಿಸಿ",
        selectedLanguage: "ಆಯ್ಕೆ ಮಾಡಿದ ಭಾಷೆ",
        languageChanged: "ಭಾಷೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ.",
        chooseLanguage: "ನಿಮಗೆ ಇಷ್ಟವಾದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        languagesAvailable: "ಭಾಷೆಗಳು ಲಭ್ಯವಿವೆ",
    },

    ml: {
        dashboard: "ഡാഷ്ബോർഡ്",
        emergency: "അടിയന്തരാവസ്ഥ / SOS",
        ambulances: "സമീപത്തുള്ള ആംബുലൻസുകൾ",
        hospitals: "സമീപത്തുള്ള ആശുപത്രികൾ",
        route: "അടിയന്തര പാത",
        medicine: "മെഡിസിൻ സ്റ്റോർ",
        history: "അടിയന്തര ചരിത്രം",
        profile: "എന്റെ പ്രൊഫൈൽ",
        language: "ഭാഷ",
        howWorks: "RESQ എങ്ങനെ പ്രവർത്തിക്കുന്നു",
        about: "RESQ-നെ കുറിച്ച്",
        logout: "ലോഗ് ഔട്ട്",
        welcome: "സ്വാഗതം",
        quickAccess: "ദ്രുത പ്രവേശനം",
        nearbyHospitals: "സമീപത്തുള്ള ആശുപത്രികൾ",
        nearbyAmbulances: "സമീപത്തുള്ള ആംബുലൻസുകൾ",
        emergencyRoute: "അടിയന്തര പാത",
        medicineStore: "മെഡിസിൻ സ്റ്റോർ",
        currentLocation: "നിലവിലെ സ്ഥാനം",
        callNow: "ഇപ്പോൾ വിളിക്കുക",
        getDirections: "വഴി കണ്ടെത്തുക",
        backDashboard: "ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക",
        saveLanguage: "ഭാഷ സംരക്ഷിക്കുക",
        selectedLanguage: "തിരഞ്ഞെടുത്ത ഭാഷ",
        languageChanged: "ഭാഷ വിജയകരമായി മാറ്റി.",
        chooseLanguage: "നിങ്ങൾക്ക് ഇഷ്ടമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക",
        languagesAvailable: "ഭാഷകൾ ലഭ്യമാണ്",
    },

    mr: {
        dashboard: "डॅशबोर्ड",
        emergency: "आपत्कालीन / SOS",
        ambulances: "जवळच्या रुग्णवाहिका",
        hospitals: "जवळची रुग्णालये",
        route: "आपत्कालीन मार्ग",
        medicine: "मेडिसिन स्टोअर",
        history: "आपत्कालीन इतिहास",
        profile: "माझे प्रोफाइल",
        language: "भाषा",
        howWorks: "RESQ कसे कार्य करते",
        about: "RESQ बद्दल",
        logout: "लॉग आउट",
        welcome: "स्वागत आहे",
        quickAccess: "जलद प्रवेश",
        nearbyHospitals: "जवळची रुग्णालये",
        nearbyAmbulances: "जवळच्या रुग्णवाहिका",
        emergencyRoute: "आपत्कालीन मार्ग",
        medicineStore: "मेडिसिन स्टोअर",
        currentLocation: "सध्याचे स्थान",
        callNow: "आता कॉल करा",
        getDirections: "दिशा मिळवा",
        backDashboard: "डॅशबोर्डवर परत जा",
        saveLanguage: "भाषा जतन करा",
        selectedLanguage: "निवडलेली भाषा",
        languageChanged: "भाषा यशस्वीरित्या बदलली.",
        chooseLanguage: "तुमची आवडती भाषा निवडा",
        languagesAvailable: "भाषा उपलब्ध आहेत",
    },

    bn: {
        dashboard: "ড্যাশবোর্ড",
        emergency: "জরুরি অবস্থা / SOS",
        ambulances: "কাছাকাছি অ্যাম্বুলেন্স",
        hospitals: "কাছাকাছি হাসপাতাল",
        route: "জরুরি পথ",
        medicine: "মেডিসিন স্টোর",
        history: "জরুরি ইতিহাস",
        profile: "আমার প্রোফাইল",
        language: "ভাষা",
        howWorks: "RESQ কীভাবে কাজ করে",
        about: "RESQ সম্পর্কে",
        logout: "লগ আউট",
        welcome: "স্বাগতম",
        quickAccess: "দ্রুত অ্যাক্সেস",
        nearbyHospitals: "কাছাকাছি হাসপাতাল",
        nearbyAmbulances: "কাছাকাছি অ্যাম্বুলেন্স",
        emergencyRoute: "জরুরি পথ",
        medicineStore: "মেডিসিন স্টোর",
        currentLocation: "বর্তমান অবস্থান",
        callNow: "এখনই কল করুন",
        getDirections: "দিকনির্দেশ পান",
        backDashboard: "ড্যাশবোর্ডে ফিরে যান",
        saveLanguage: "ভাষা সংরক্ষণ করুন",
        selectedLanguage: "নির্বাচিত ভাষা",
        languageChanged: "ভাষা সফলভাবে পরিবর্তন হয়েছে।",
        chooseLanguage: "আপনার পছন্দের ভাষা নির্বাচন করুন",
        languagesAvailable: "টি ভাষা উপলব্ধ",
    },
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(
        localStorage.getItem("resqLanguage") || "en"
    );

    useEffect(() => {
        localStorage.setItem("resqLanguage", language);
        document.documentElement.lang = language;
    }, [language]);

    const changeLanguage = (newLanguage) => {
        setLanguage(newLanguage);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    };

    return (
        <LanguageContext.Provider
            value={{
                language,
                changeLanguage,
                t,
                translations,
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}